# Generated by Django 6.0 on 2025-12-27 12:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], help_text='Day of week', max_length=3)),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(help_text='End time')),
                ('location', models.CharField(blank=True, help_text='Class location/room', max_length=255)),
                ('semester', models.CharField(help_text='Semester for schedule', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course in schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course')),
                ('student', models.ForeignKey(help_text='Student user', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
                'ordering': ['semester', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A (4.0)'), ('A-', 'A- (3.7)'), ('B+', 'B+ (3.3)'), ('B', 'B (3.0)'), ('B-', 'B- (2.7)'), ('C+', 'C+ (2.3)'), ('C', 'C (2.0)'), ('D', 'D (1.0)'), ('F', 'F (0.0)'), ('W', 'W (Withdrawal)')], help_text='Grade received', max_length=3)),
                ('grade_points', models.FloatField(help_text='Grade points (0.0-4.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('semester', models.CharField(help_text='Semester taken (e.g., Spring 1402, Fall 1401)', max_length=10)),
                ('credits_earned', models.IntegerField(default=0, help_text='Credits earned (0 if failed)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('is_passed', models.BooleanField(default=True, help_text='Is course passed?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course taken', on_delete=django.db.models.deletion.CASCADE, related_name='student_histories', to='courses.course')),
                ('student', models.ForeignKey(help_text='Student user', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student course history',
                'verbose_name_plural': 'student course histories',
                'ordering': ['-semester', '-created_at'],
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='StudentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='Semester for selection (e.g., Spring 1403)', max_length=10)),
                ('selected_at', models.DateTimeField(auto_now_add=True, help_text='Date of selection')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Is selection confirmed by student?')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Date of confirmation', null=True)),
                ('notes', models.TextField(blank=True, help_text='Student notes for this course selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Selected course', on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='courses.course')),
                ('student', models.ForeignKey(help_text='Student user', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student course selection',
                'verbose_name_plural': 'student course selections',
                'ordering': ['-selected_at'],
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
