# Generated by Django 6.0 on 2025-12-27 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name', max_length=255)),
                ('code', models.CharField(help_text='Course code (e.g., CS101)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('credits', models.IntegerField(help_text='Number of credits', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('unit_type', models.CharField(choices=[('theory', 'Theoretical'), ('practical', 'Practical'), ('both', 'Theory + Practical')], default='both', help_text='Type of course', max_length=20)),
                ('theoretical_units', models.IntegerField(default=0, help_text='Number of theoretical units/hours per week')),
                ('practical_units', models.IntegerField(default=0, help_text='Number of practical units/hours per week')),
                ('day_of_week', models.CharField(blank=True, help_text='Day of week (Sat, Sun, Mon, Tue, Wed, Thu)', max_length=20)),
                ('start_time', models.TimeField(blank=True, help_text='Start time of the course', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time of the course', null=True)),
                ('semester', models.IntegerField(blank=True, help_text='Recommended semester (1-8)', null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Is this course mandatory for the degree?')),
                ('is_offered', models.BooleanField(default=True, help_text='Is this course currently being offered?')),
                ('instructor', models.CharField(blank=True, help_text='Instructor/Professor name', max_length=255)),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum student capacity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DegreeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the degree program (e.g., Computer Science)', max_length=255)),
                ('code', models.CharField(help_text='Unique code for the degree program', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the degree program')),
                ('department', models.CharField(help_text='Department name', max_length=255)),
                ('total_credits', models.IntegerField(default=120, help_text='Total credits required for this degree', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'degree chart',
                'verbose_name_plural': 'degree charts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corequisite_course', models.ForeignKey(help_text='The course that must be taken at the same time', on_delete=django.db.models.deletion.CASCADE, related_name='corequisites_of', to='courses.course')),
                ('course', models.ForeignKey(help_text='The course that requires co-requisites', on_delete=django.db.models.deletion.CASCADE, related_name='corequisites_for', to='courses.course')),
            ],
            options={
                'verbose_name': 'co-requisite',
                'verbose_name_plural': 'co-requisites',
                'unique_together': {('course', 'corequisite_course')},
            },
        ),
        migrations.CreateModel(
            name='ChartCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Is this course mandatory for this program?')),
                ('recommended_semester', models.IntegerField(blank=True, help_text='Recommended semester to take this course', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('importance_score', models.FloatField(default=0.0, help_text='Calculated importance score (# of dependent courses)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='The course', on_delete=django.db.models.deletion.CASCADE, related_name='chart_offerings', to='courses.course')),
                ('degree_chart', models.ForeignKey(help_text='The degree program', on_delete=django.db.models.deletion.CASCADE, related_name='chart_courses', to='courses.degreechart')),
            ],
            options={
                'verbose_name': 'chart course',
                'verbose_name_plural': 'chart courses',
                'ordering': ['recommended_semester', 'course__code'],
                'unique_together': {('degree_chart', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_corequisite', models.BooleanField(default=False, help_text='Is this a co-requisite? (can be taken at the same time)')),
                ('min_grade', models.CharField(default='D', help_text='Minimum grade required in prerequisite (A, B, C, D)', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='The course that requires prerequisites', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_for', to='courses.course')),
                ('prerequisite_course', models.ForeignKey(help_text='The course that must be completed first', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_of', to='courses.course')),
            ],
            options={
                'verbose_name': 'prerequisite',
                'verbose_name_plural': 'prerequisites',
                'unique_together': {('course', 'prerequisite_course')},
            },
        ),
    ]
