# Generated by Django 4.2.11 on 2026-01-02 20:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_passed_units', models.IntegerField(help_text='Minimum units that must be passed before this course', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'course requirement',
                'verbose_name_plural': 'course requirements',
            },
        ),
        migrations.AlterModelOptions(
            name='degreechart',
            options={'ordering': ['-start_year', 'name'], 'verbose_name': 'degree chart', 'verbose_name_plural': 'degree charts'},
        ),
        migrations.AddField(
            model_name='degreechart',
            name='end_year',
            field=models.IntegerField(default=1402, help_text='Last entry year this degree chart applies to (e.g., 1402)'),
        ),
        migrations.AddField(
            model_name='degreechart',
            name='field_code',
            field=models.CharField(default='102', help_text='Field code for student IDs (e.g., 102 for CS)', max_length=10),
        ),
        migrations.AddField(
            model_name='degreechart',
            name='level',
            field=models.CharField(choices=[('12', 'کارشناسی (Bachelor)'), ('13', 'کارشناسی ارشد (Masters)'), ('14', 'دکتری (PhD)')], default='12', help_text='Education level', max_length=20),
        ),
        migrations.AddField(
            model_name='degreechart',
            name='start_year',
            field=models.IntegerField(default=1392, help_text='First entry year this degree chart applies to (e.g., 1392)'),
        ),
        migrations.AlterField(
            model_name='chartcourse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='corequisite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='degreechart',
            name='code',
            field=models.CharField(help_text='Unique code for the degree program (e.g., CS-BS-92-402)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='degreechart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='degreechart',
            index=models.Index(fields=['field_code', 'level'], name='courses_deg_field_c_2d6b44_idx'),
        ),
        migrations.AddIndex(
            model_name='degreechart',
            index=models.Index(fields=['start_year', 'end_year'], name='courses_deg_start_y_ba8a81_idx'),
        ),
        migrations.AddField(
            model_name='courserequirement',
            name='course',
            field=models.ForeignKey(help_text='The course that has unit requirement', on_delete=django.db.models.deletion.CASCADE, related_name='unit_requirements', to='courses.course'),
        ),
        migrations.AlterUniqueTogether(
            name='courserequirement',
            unique_together={('course', 'min_passed_units')},
        ),
    ]
