# Generated by Django 4.2.11 on 2026-01-02 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courserequirement_alter_degreechart_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group name (e.g., Technical Electives)', max_length=255)),
                ('code', models.CharField(help_text='Unique code (e.g., TECH-ELECTIVE)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this group contains')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(help_text='Courses available in this group', related_name='course_groups', to='courses.course')),
            ],
            options={
                'verbose_name': 'course group',
                'verbose_name_plural': 'course groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChartSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g., مهندسی کامپیوتر - کارشناسی)', max_length=255)),
                ('code', models.CharField(help_text='Schema code (e.g., CS-BS-92-402)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this degree program version')),
                ('major', models.CharField(choices=[('CS', 'مهندسی کامپیوتر (Computer Science)'), ('EE', 'مهندسی برق (Electrical Engineering)'), ('CE', 'مهندسی عمران (Civil Engineering)'), ('ME', 'مهندسی مکانیک (Mechanical Engineering)'), ('SE', 'مهندسی نرم\u200cافزار (Software Engineering)')], help_text='Field of study', max_length=20)),
                ('degree', models.CharField(choices=[('12', 'کارشناسی (Bachelor)'), ('13', 'کارشناسی ارشد (Masters)'), ('14', 'دکتری (PhD)')], default='12', help_text='Degree level', max_length=20)),
                ('entry_year_start', models.IntegerField(help_text='First entry year (e.g., 1392)', validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1500)])),
                ('entry_year_end', models.IntegerField(help_text='Last entry year (e.g., 1402)', validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1500)])),
                ('total_credits', models.IntegerField(default=120, help_text='Total credits required', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this schema currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'chart schema',
                'verbose_name_plural': 'chart schemas',
                'ordering': ['-entry_year_start', 'major'],
                'indexes': [models.Index(fields=['major', 'degree'], name='courses_cha_major_b39f47_idx'), models.Index(fields=['entry_year_start', 'entry_year_end'], name='courses_cha_entry_y_ed2467_idx')],
                'unique_together': {('major', 'degree', 'entry_year_start', 'entry_year_end')},
            },
        ),
        migrations.CreateModel(
            name='ChartNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(help_text='Semester number (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('position', models.IntegerField(default=0, help_text='Display order within semester')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Is this course/group mandatory?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='If specified, this is a required course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_nodes_specific', to='courses.course')),
                ('course_group', models.ForeignKey(blank=True, help_text='If specified, student chooses one from this group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_nodes', to='courses.coursegroup')),
                ('schema', models.ForeignKey(help_text='The chart schema this node belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='courses.chartschema')),
            ],
            options={
                'verbose_name': 'chart node',
                'verbose_name_plural': 'chart nodes',
                'ordering': ['semester', 'position'],
                'unique_together': {('schema', 'semester', 'position')},
            },
        ),
    ]
